kind: ServiceAccount
apiVersion: v1
metadata:
  name: blinkt-k8s-controller-sa
  namespace: kube-system
  labels:
    app: blinkt-k8s-controller-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: blinkt-k8s-controller-sa
  namespace: kube-system
  labels:
    app: blinkt-k8s-controller-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: blinkt-k8s-controller-sa
  namespace: kube-system
