kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
api:
  advertiseAddress: 10.0.254.1
networking:
  podSubnet: 10.244.0.0/16
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "false"
