kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: load-simulator-sa
  name: load-simulator-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: load-simulator-sa
  labels:
    app: load-simulator-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: load-simulator-sa
  namespace: default
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: load-simulator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: load-simulator
    spec:
      serviceAccountName: load-simulator-sa
      hostAliases:
      - ip: "10.88.1.1"
        hostnames:
        - "pi.cluster"
      containers:
      - image: ngpitt/load-simulator:v1
        name: load-simulator
        args:
        - -url=http://pi.cluster:30080/?digits=1000
        - -clients=8
        - -hpa=pi
        env:
        - name: GLOG_logtostderr
          value: "1"
