kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi
  template:
    metadata:
      labels:
        app: pi
        blinktShow: "true"
        blinktColor: cpu
    spec:
      containers:
      - image: ngpitt/pi:v1
        name: pi
        resources:
          requests:
            cpu: 1
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: pi
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pi
  minReplicas: 1
  maxReplicas: 32
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
kind: Service
apiVersion: v1
metadata:
  name: pi
spec:
  selector:
    app: pi
  ports:
  - port: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: pi
spec:
  rules:
  - host: pi.cluster
    http:
      paths:
      - path: /
        backend:
          serviceName: pi
          servicePort: 80
